// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: sender/sender.proto

package sender

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (x *InMessage) Reset() {
	*x = InMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sender_sender_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InMessage) ProtoMessage() {}

func (x *InMessage) ProtoReflect() protoreflect.Message {
	mi := &file_sender_sender_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InMessage.ProtoReflect.Descriptor instead.
func (*InMessage) Descriptor() ([]byte, []int) {
	return file_sender_sender_proto_rawDescGZIP(), []int{0}
}

func (x *InMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type OutMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (x *OutMessage) Reset() {
	*x = OutMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sender_sender_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OutMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutMessage) ProtoMessage() {}

func (x *OutMessage) ProtoReflect() protoreflect.Message {
	mi := &file_sender_sender_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutMessage.ProtoReflect.Descriptor instead.
func (*OutMessage) Descriptor() ([]byte, []int) {
	return file_sender_sender_proto_rawDescGZIP(), []int{1}
}

func (x *OutMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_sender_sender_proto protoreflect.FileDescriptor

var file_sender_sender_proto_rawDesc = []byte{
	0x0a, 0x13, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x2f, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x22, 0x25, 0x0a,
	0x09, 0x49, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x22, 0x26, 0x0a, 0x0a, 0x4f, 0x75, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x3e, 0x0a, 0x06,
	0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x34, 0x0a, 0x0b, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x11, 0x2e, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x49,
	0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x12, 0x2e, 0x73, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x2e, 0x4f, 0x75, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x11, 0x5a, 0x0f,
	0x2e, 0x2f, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x3b, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sender_sender_proto_rawDescOnce sync.Once
	file_sender_sender_proto_rawDescData = file_sender_sender_proto_rawDesc
)

func file_sender_sender_proto_rawDescGZIP() []byte {
	file_sender_sender_proto_rawDescOnce.Do(func() {
		file_sender_sender_proto_rawDescData = protoimpl.X.CompressGZIP(file_sender_sender_proto_rawDescData)
	})
	return file_sender_sender_proto_rawDescData
}

var file_sender_sender_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sender_sender_proto_goTypes = []interface{}{
	(*InMessage)(nil),  // 0: sender.InMessage
	(*OutMessage)(nil), // 1: sender.OutMessage
}
var file_sender_sender_proto_depIdxs = []int32{
	0, // 0: sender.Sender.SendMessage:input_type -> sender.InMessage
	1, // 1: sender.Sender.SendMessage:output_type -> sender.OutMessage
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sender_sender_proto_init() }
func file_sender_sender_proto_init() {
	if File_sender_sender_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sender_sender_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sender_sender_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OutMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sender_sender_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sender_sender_proto_goTypes,
		DependencyIndexes: file_sender_sender_proto_depIdxs,
		MessageInfos:      file_sender_sender_proto_msgTypes,
	}.Build()
	File_sender_sender_proto = out.File
	file_sender_sender_proto_rawDesc = nil
	file_sender_sender_proto_goTypes = nil
	file_sender_sender_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SenderClient is the client API for Sender service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SenderClient interface {
	SendMessage(ctx context.Context, in *InMessage, opts ...grpc.CallOption) (*OutMessage, error)
}

type senderClient struct {
	cc grpc.ClientConnInterface
}

func NewSenderClient(cc grpc.ClientConnInterface) SenderClient {
	return &senderClient{cc}
}

func (c *senderClient) SendMessage(ctx context.Context, in *InMessage, opts ...grpc.CallOption) (*OutMessage, error) {
	out := new(OutMessage)
	err := c.cc.Invoke(ctx, "/sender.Sender/SendMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SenderServer is the server API for Sender service.
type SenderServer interface {
	SendMessage(context.Context, *InMessage) (*OutMessage, error)
}

// UnimplementedSenderServer can be embedded to have forward compatible implementations.
type UnimplementedSenderServer struct {
}

func (*UnimplementedSenderServer) SendMessage(context.Context, *InMessage) (*OutMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}

func RegisterSenderServer(s *grpc.Server, srv SenderServer) {
	s.RegisterService(&_Sender_serviceDesc, srv)
}

func _Sender_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SenderServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sender.Sender/SendMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SenderServer).SendMessage(ctx, req.(*InMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Sender_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sender.Sender",
	HandlerType: (*SenderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _Sender_SendMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sender/sender.proto",
}
